package exceptions

class UserAlreadyExistsException: Exception("Пользователь уже существует")